python test_flow.py --category chair --model /logs/PSF/chair/output/train_flow/2024-07-01-11-07-26/final.pth --step 1 --saving_folder chair_outputs
python test_flow.py --category chair --model /logs/PSF/chair/output/train_flow/2024-07-01-11-07-26/final.pth --step 2 --saving_folder chair_outputs
python test_flow.py --category chair --model /logs/PSF/chair/output/train_flow/2024-07-01-11-07-26/final.pth --step 5 --saving_folder chair_outputs
python test_flow.py --category chair --model /logs/PSF/chair/output/train_flow/2024-07-01-11-07-26/final.pth --step 10 --saving_folder chair_outputs
python test_flow.py --category chair --model /logs/PSF/chair/output/train_flow/2024-07-01-11-07-26/final.pth --step 20 --saving_folder chair_outputs
python test_flow.py --category chair --model /logs/PSF/chair/output/train_flow/2024-07-01-11-07-26/final.pth --step 50 --saving_folder chair_outputs
python test_flow.py --category chair --model /logs/PSF/chair/output/train_flow/2024-07-01-11-07-26/final.pth --step 100 --saving_folder chair_outputs
python test_flow.py --category airplane --model /logs/PSF/airplane/output/train_flow/epoch_19991.pth --step 1 --saving_folder airplane_outputs
python test_flow.py --category airplane --model /logs/PSF/airplane/output/train_flow/epoch_19991.pth --step 2 --saving_folder airplane_outputs
python test_flow.py --category airplane --model /logs/PSF/airplane/output/train_flow/epoch_19991.pth --step 5 --saving_folder airplane_outputs
python test_flow.py --category airplane --model /logs/PSF/airplane/output/train_flow/epoch_19991.pth --step 10 --saving_folder airplane_outputs
python test_flow.py --category airplane --model /logs/PSF/airplane/output/train_flow/epoch_19991.pth --step 20 --saving_folder airplane_outputs
python test_flow.py --category airplane --model /logs/PSF/airplane/output/train_flow/epoch_19991.pth --step 50 --saving_folder airplane_outputs
python test_flow.py --category airplane --model /logs/PSF/airplane/output/train_flow/epoch_19991.pth --step 100 --saving_folder airplane_outputs
python test_flow.py --category car --model /logs/PSF/car/output/train_flow/epoch_19991.pth --step 1 --saving_folder car_outputs
python test_flow.py --category car --model /logs/PSF/car/output/train_flow/epoch_19991.pth --step 2 --saving_folder car_outputs
python test_flow.py --category car --model /logs/PSF/car/output/train_flow/epoch_19991.pth --step 5 --saving_folder car_outputs
python test_flow.py --category car --model /logs/PSF/car/output/train_flow/epoch_19991.pth --step 10 --saving_folder car_outputs
python test_flow.py --category car --model /logs/PSF/car/output/train_flow/epoch_19991.pth --step 20 --saving_folder car_outputs
python test_flow.py --category car --model /logs/PSF/car/output/train_flow/epoch_19991.pth --step 50 --saving_folder car_outputs
python test_flow.py --category car --model /logs/PSF/car/output/train_flow/epoch_19991.pth --step 100 --saving_folder car_outputs
